#### TF-IDF Vectorization

Term Frequency Inverse document Frequency

#### POS Tagging & Context-Free Grammar

POS (Part-of-Speech Tagging)

### Twitter Sentiment Analysis

We will look at a classification problem using tweets scrapped of the X plattform. The original dataset comes in kaggle.

In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [125]:
#leading the dataset
raw_df =  pd.read_csv('twitter_training.csv', header=None, names=['id', 'topic', 'sentiment', 'tweet'])

raw_df.head(10)

,id,topic,sentiment,tweet
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
5,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
6,2402,Borderlands,Positive,So I spent a few hours making something for fu...
7,2402,Borderlands,Positive,So I spent a couple of hours doing something f...
8,2402,Borderlands,Positive,So I spent a few hours doing something for fun...
9,2402,Borderlands,Positive,So I spent a few hours making something for fu...

In [126]:
raw_df.shape

(74682, 4)

In [127]:
# check any non value
raw_df.isnull().sum()

id             0
topic          0
sentiment      0
tweet        686
dtype: int64

In [128]:
# drop the rows with null values or null entries
df = raw_df.dropna()

df.isnull().sum()

id           0
topic        0
sentiment    0
tweet        0
dtype: int64

In [129]:
df['tweet'].iloc()

In [130]:
# remove hashtags#, urls, @ clean up, convert data to lower case.

import re

# urls
pat_1 = r'https:/S+|www\.\s+'
# hashtages and mentions
pat_2 = r'#\w+|@\w+'
# punctuations and hashtags
pat_3 = r'[^a-z\s]'

In [131]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


STOPWORDS = set(stopwords.words('english'))

def cleaner(text):
    """ 
    lowercase, then remove the defined patterns from the tweets
    """
    if not isinstance(text, str):
        return 'This is not a valid tweet(text)!!!'
    
    text = text.lower()

    #remove url
    text = re.sub(pat_1, '',text)

    #remove mentions and hashtags
    text = re.sub(pat_2, '',text)

    #remove punctuations and random numbers
    text = re.sub(pat_3, '',text)


    tokens = word_tokenize(text)

    #list comprehension on tokens to remove stop words
    tokens = [token for token in tokens if token not in STOPWORDS and len(token) > 2]

    return " ".join(tokens)

In [132]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

STOPWORDS = set(stopwords.words('english'))

def cleaner(text):
    """ 
    lowercase, then remove the defined patterns from the tweets
    """
    if not isinstance(text, str):
        return 'This is not a valid tweet(text)!!!'
    
    text = text.lower()

    # remove url
    text = re.sub(pat_1, '', text)

    # remove mentions and hashtags
    text = re.sub(pat_2, '', text)

    # remove punctuations and random numbers
    text = re.sub(pat_3, '', text)

    tokens = word_tokenize(text)

    # remove stopwords and short words
    tokens = [token for token in tokens if token not in STOPWORDS and len(token) > 2]

    return " ".join(tokens)

In [133]:
cleaner('@brian is GOOGLING the world tallest building www.google.com #globalwarming')

'googling world tallest building wwwgooglecom'

In [134]:
df['sentiment'].value_counts()

sentiment
Negative      22358
Positive      20655
Neutral       18108
Irrelevant    12875
Name: count, dtype: int64

In [135]:
df['cleaned_tweets'] = df['tweet'].apply(cleaner)

print(df['tweet'].iloc[12])
print(df['cleaned_tweets'].iloc[12])

Rock-Hard La Varlope, RARE & POWERFUL, HANDSOME JACKPOT, Borderlands 3 (Xbox) dlvr.it/RMTrgF
rockhard varlope rare powerful handsome jackpot borderlands xbox dlvritrmtrgf

C:\Users\geoff\AppData\Local\Temp\ipykernel_25888\1574883476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_tweets'] = df['tweet'].apply(cleaner)

In [136]:
df.head(10)

,id,topic,sentiment,tweet,cleaned_tweets
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,getting borderlands murder
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,coming borders kill
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,getting borderlands kill
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,coming borderlands murder
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,getting borderlands murder
5,2401,Borderlands,Positive,im getting into borderlands and i can murder y...,getting borderlands murder
6,2402,Borderlands,Positive,So I spent a few hours making something for fu...,spent hours making something fun dont know hug...
7,2402,Borderlands,Positive,So I spent a couple of hours doing something f...,spent couple hours something fun dont know hug...
8,2402,Borderlands,Positive,So I spent a few hours doing something for fun...,spent hours something fun dont know huge borde...
9,2402,Borderlands,Positive,So I spent a few hours making something for fu...,spent hours making something fun dont know hug...

In [137]:
df= df.dropna()
df.isnull().sum()

id                0
topic             0
sentiment         0
tweet             0
cleaned_tweets    0
dtype: int64

In [138]:
df = df.drop_duplicates(subset='cleaned_tweets')
df.head(10)

,id,topic,sentiment,tweet,cleaned_tweets
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,getting borderlands murder
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,coming borders kill
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,getting borderlands kill
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,coming borderlands murder
6,2402,Borderlands,Positive,So I spent a few hours making something for fu...,spent hours making something fun dont know hug...
7,2402,Borderlands,Positive,So I spent a couple of hours doing something f...,spent couple hours something fun dont know hug...
8,2402,Borderlands,Positive,So I spent a few hours doing something for fun...,spent hours something fun dont know huge borde...
9,2402,Borderlands,Positive,So I spent a few hours making something for fu...,spent hours making something fun dont know hug...
11,2402,Borderlands,Positive,was,
12,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM...",rockhard varlope rare powerful handsome jackpo...

In [139]:
df['sentiment'].value_counts()

sentiment
Negative      18689
Positive      16199
Neutral       15487
Irrelevant    10859
Name: count, dtype: int64